// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";

dotenv.config({
  path: process.env.NODE_ENV === "test"
      ? ".env.test"
      : ".env"
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  }
});
